#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

# Location of app source files.
SOURCE_DIR=restic

# Run static analysis for Python bugs/cruft.
pyflakes "${SOURCE_DIR}/"
