#!/bin/bash

# Exit build script on first failure.
set -e

# Echo commands to stdout.
set -x

# Exit on unset variable.
set -u

# Location of app source files.
readonly SOURCE_DIR=restic

# Location of virtualenv.
readonly VIRTUALENV_DIR=venv

# Check that source has correct formatting.
yapf \
  --diff \
  --recursive \
  --style google \
  ./ \
  --exclude="${VIRTUALENV_DIR}/*"

# Run static analysis for Python bugs/cruft.
pyflakes "${SOURCE_DIR}/"
